import {
    TAdSetsTable,
    TAdsTable,
    TAdvertisementTable,
    TCampaignTable,
} from "../models/advertisement/advertisement";
import { SelectType } from "../models/common";
import { TSystemTable } from "../models/system/system";

export const fakeSystemTableData: TSystemTable[] = [
    {
        id: "1",
        name: "Công ty cổ phần ABC",
        description: "Công ty chuyên về sản xuất và kinh doanh ABC",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "2",
        name: "Công ty cổ phần BCD",
        description:
            "Công ty chuyên cung cấp dịch vụ BCD trong ngành công nghiệp",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "3",
        name: "Công ty cổ phần EFG",
        description: "Công ty nổi tiếng với sản phẩm công nghệ EFG",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "4",
        name: "Công ty cổ phần XYZ",
        description: "Công ty dẫn đầu trong lĩnh vực phát triển phần mềm XYZ",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "5",
        name: "Công ty cổ phần UVW",
        description: "Công ty chuyên về giải pháp UVW cho doanh nghiệp",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "6",
        name: "Công ty cổ phần RST",
        description: "Công ty hoạt động trong lĩnh vực tài chính RST",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "7",
        name: "Công ty cổ phần LMN",
        description: "Công ty cung cấp dịch vụ viễn thông LMN",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "8",
        name: "Công ty cổ phần OPQ",
        description: "Công ty phát triển công nghệ tiên tiến OPQ",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "9",
        name: "Công ty cổ phần HJK",
        description:
            "Công ty hoạt động trong lĩnh vực sản xuất hàng tiêu dùng HJK",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "10",
        name: "Công ty cổ phần VWX",
        description: "Công ty nổi tiếng với sản phẩm công nghệ VWX",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "11",
        name: "Công ty cổ phần YZA",
        description: "Công ty cung cấp giải pháp môi trường YZA",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "12",
        name: "Công ty cổ phần BNM",
        description:
            "Công ty dẫn đầu trong lĩnh vực sản xuất và kinh doanh BNM",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
];

export const fakeSelectSystemData: SelectType[] = [
    {
        value: "1",
        label: "Công ty cổ phần VWX",
    },
    {
        value: "2",
        label: "Công ty cổ phần BNM",
    },
    {
        value: "3",
        label: "Công ty cổ phần OPQ",
    },
];

export const fakeSelectAgencyData: SelectType[] = [
    {
        value: "1",
        label: "Chi nhánh cổ phần ABC",
    },
    {
        value: "2",
        label: "Chi nhánh cổ phần DEF",
    },
    {
        value: "3",
        label: "Chi nhánh cổ phần GHI",
    },
];

export const fakeSelectTeamData: SelectType[] = [
    {
        value: "1",
        label: "Đội 1",
    },
    {
        value: "2",
        label: "Đội 2",
    },
    {
        value: "3",
        label: "Đội 3",
    },
];

export const fakeSelectMemberData: SelectType[] = [
    {
        value: "1",
        label: "Member 1",
    },
    {
        value: "2",
        label: "Member 2",
    },
    {
        value: "3",
        label: "Member 3",
    },
];

export const fakeAdvertisementTableData: TAdvertisementTable[] = [];

export const fakeCampaignTableData: TCampaignTable[] = [
    {
        id: "campaign_1",
        name: "Chiến dịch A",
        budget_rebalance_flag: true,
        buying_type: "Auction",
        created_time: "2024-05-01T08:30:00",
        start_time: "2024-06-01T00:00:00",
        effective_status: "ACTIVE",
        configured_status: "ACTIVE",
        status: "ACTIVE",
        account_id: "account_101",
        budget_remaining: "5000 USD",
        special_ad_category_country: ["US", "CA"],
        updated_time: "2024-09-01T10:00:00",
    },
    {
        id: "campaign_2",
        name: "Chiến dịch B",
        budget_rebalance_flag: false,
        buying_type: "Fixed",
        created_time: "2024-02-15T09:45:00",
        start_time: "2024-03-01T00:00:00",
        effective_status: "PAUSED",
        configured_status: "PAUSED",
        status: "PAUSED",
        account_id: "account_102",
        budget_remaining: "2000 USD",
        special_ad_category_country: ["GB"],
        updated_time: "2024-08-25T14:30:00",
    },
    {
        id: "campaign_3",
        name: "Chiến dịch C",
        budget_rebalance_flag: true,
        buying_type: "Auction",
        created_time: "2024-07-20T11:15:00",
        start_time: "2024-08-01T00:00:00",
        effective_status: "ACTIVE",
        configured_status: "ACTIVE",
        status: "ACTIVE",
        account_id: "account_103",
        budget_remaining: "7500 USD",
        special_ad_category_country: ["AU", "NZ"],
        updated_time: "2024-09-02T12:00:00",
    },
    {
        id: "campaign_4",
        name: "Chiến dịch D",
        budget_rebalance_flag: false,
        buying_type: "Auction",
        created_time: "2024-04-01T10:00:00",
        start_time: "2024-05-01T00:00:00",
        effective_status: "INACTIVE",
        configured_status: "INACTIVE",
        status: "INACTIVE",
        account_id: "account_104",
        budget_remaining: "0 USD",
        special_ad_category_country: ["US"],
        updated_time: "2024-07-15T09:20:00",
    },
    {
        id: "campaign_5",
        name: "Chiến dịch E",
        budget_rebalance_flag: true,
        buying_type: "Fixed",
        created_time: "2024-03-10T14:00:00",
        start_time: "2024-04-01T00:00:00",
        effective_status: "ACTIVE",
        configured_status: "ACTIVE",
        status: "ACTIVE",
        account_id: "account_105",
        budget_remaining: "3000 USD",
        special_ad_category_country: ["DE"],
        updated_time: "2024-09-03T16:30:00",
    },
    {
        id: "campaign_6",
        name: "Chiến dịch F",
        budget_rebalance_flag: false,
        buying_type: "Auction",
        created_time: "2024-01-20T15:45:00",
        start_time: "2024-02-01T00:00:00",
        effective_status: "PAUSED",
        configured_status: "PAUSED",
        status: "PAUSED",
        account_id: "account_106",
        budget_remaining: "1500 USD",
        special_ad_category_country: ["FR", "IT"],
        updated_time: "2024-09-05T11:40:00",
    },
    {
        id: "campaign_7",
        name: "Chiến dịch G",
        budget_rebalance_flag: true,
        buying_type: "Auction",
        created_time: "2024-06-01T12:30:00",
        start_time: "2024-07-01T00:00:00",
        effective_status: "ACTIVE",
        configured_status: "ACTIVE",
        status: "ACTIVE",
        account_id: "account_107",
        budget_remaining: "6000 USD",
        special_ad_category_country: ["JP"],
        updated_time: "2024-09-06T10:00:00",
    },
    {
        id: "campaign_8",
        name: "Chiến dịch H",
        budget_rebalance_flag: false,
        buying_type: "Fixed",
        created_time: "2024-05-15T13:15:00",
        start_time: "2024-06-01T00:00:00",
        effective_status: "INACTIVE",
        configured_status: "INACTIVE",
        status: "INACTIVE",
        account_id: "account_108",
        budget_remaining: "0 USD",
        special_ad_category_country: ["CN"],
        updated_time: "2024-08-10T09:50:00",
    },
    {
        id: "campaign_9",
        name: "Chiến dịch I",
        budget_rebalance_flag: true,
        buying_type: "Auction",
        created_time: "2024-07-05T16:00:00",
        start_time: "2024-08-01T00:00:00",
        effective_status: "ACTIVE",
        configured_status: "ACTIVE",
        status: "ACTIVE",
        account_id: "account_109",
        budget_remaining: "4500 USD",
        special_ad_category_country: ["KR"],
        updated_time: "2024-09-07T14:10:00",
    },
    {
        id: "campaign_10",
        name: "Chiến dịch J",
        budget_rebalance_flag: false,
        buying_type: "Fixed",
        created_time: "2024-03-25T09:30:00",
        start_time: "2024-04-01T00:00:00",
        effective_status: "PAUSED",
        configured_status: "PAUSED",
        status: "PAUSED",
        account_id: "account_110",
        budget_remaining: "1000 USD",
        special_ad_category_country: ["BR"],
        updated_time: "2024-09-08T13:20:00",
    },
];

export const fakeAdSetsTableData: TAdSetsTable[] = [
    {
        id: "1",
        lifetime_imps: 1000000,
        name: "Ad Set 1",
        targeting: {
            age_max: 35,
            age_min: 18,
            geo_locations: {
                countries: ["US", "CA"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Facebook", "Instagram"],
            facebook_positions: ["Feed", "Story"],
            device_platforms: ["Mobile", "Desktop"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-01-01T00:00:00",
        budget_remaining: "5000 USD",
        configured_status: "ACTIVE",
        created_time: "2023-12-01T12:00:00",
        daily_budget: "100 USD",
        lifetime_budget: "5000 USD",
        promoted_object: {
            page_id: "page_123",
        },
        status: "ACTIVE",
        updated_time: "2024-01-10T10:00:00",
        campaign: {
            id: "campaign_1",
        },
        campaign_id: "campaign_1",
    },
    {
        id: "2",
        lifetime_imps: 1500000,
        name: "Ad Set 2",
        targeting: {
            age_max: 45,
            age_min: 25,
            geo_locations: {
                countries: ["GB", "AU"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Facebook"],
            facebook_positions: ["Feed"],
            device_platforms: ["Desktop"],
        },
        effective_status: "PAUSED",
        start_time: "2024-02-01T00:00:00",
        budget_remaining: "3000 USD",
        configured_status: "PAUSED",
        created_time: "2023-11-01T12:00:00",
        daily_budget: "50 USD",
        lifetime_budget: "3000 USD",
        promoted_object: {
            page_id: "page_456",
        },
        status: "PAUSED",
        updated_time: "2024-02-15T10:00:00",
        campaign: {
            id: "campaign_2",
        },
        campaign_id: "campaign_2",
    },
    {
        id: "3",
        lifetime_imps: 2000000,
        name: "Ad Set 3",
        targeting: {
            age_max: 30,
            age_min: 20,
            geo_locations: {
                countries: ["FR", "DE"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Instagram"],
            facebook_positions: ["Story"],
            device_platforms: ["Mobile"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-03-01T00:00:00",
        budget_remaining: "8000 USD",
        configured_status: "ACTIVE",
        created_time: "2023-10-01T12:00:00",
        daily_budget: "200 USD",
        lifetime_budget: "8000 USD",
        promoted_object: {
            page_id: "page_789",
        },
        status: "ACTIVE",
        updated_time: "2024-03-05T10:00:00",
        campaign: {
            id: "campaign_3",
        },
        campaign_id: "campaign_3",
    },
    {
        id: "4",
        lifetime_imps: 500000,
        name: "Ad Set 4",
        targeting: {
            age_max: 40,
            age_min: 30,
            geo_locations: {
                countries: ["IT", "ES"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Facebook", "Instagram"],
            facebook_positions: ["Feed"],
            device_platforms: ["Mobile", "Desktop"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-04-01T00:00:00",
        budget_remaining: "2000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-01-01T12:00:00",
        daily_budget: "50 USD",
        lifetime_budget: "2000 USD",
        promoted_object: {
            page_id: "page_101",
        },
        status: "ACTIVE",
        updated_time: "2024-04-10T10:00:00",
        campaign: {
            id: "campaign_4",
        },
        campaign_id: "campaign_4",
    },
    {
        id: "5",
        lifetime_imps: 750000,
        name: "Ad Set 5",
        targeting: {
            age_max: 50,
            age_min: 40,
            geo_locations: {
                countries: ["JP", "KR"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Facebook"],
            facebook_positions: ["Feed"],
            device_platforms: ["Desktop"],
        },
        effective_status: "PAUSED",
        start_time: "2024-05-01T00:00:00",
        budget_remaining: "1500 USD",
        configured_status: "PAUSED",
        created_time: "2023-12-01T12:00:00",
        daily_budget: "30 USD",
        lifetime_budget: "1500 USD",
        promoted_object: {
            page_id: "page_202",
        },
        status: "PAUSED",
        updated_time: "2024-05-15T10:00:00",
        campaign: {
            id: "campaign_5",
        },
        campaign_id: "campaign_5",
    },
    {
        id: "6",
        lifetime_imps: 3000000,
        name: "Ad Set 6",
        targeting: {
            age_max: 60,
            age_min: 30,
            geo_locations: {
                countries: ["BR", "AR"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Instagram"],
            facebook_positions: ["Story"],
            device_platforms: ["Mobile"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-06-01T00:00:00",
        budget_remaining: "10000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-02-01T12:00:00",
        daily_budget: "500 USD",
        lifetime_budget: "10000 USD",
        promoted_object: {
            page_id: "page_303",
        },
        status: "ACTIVE",
        updated_time: "2024-06-05T10:00:00",
        campaign: {
            id: "campaign_6",
        },
        campaign_id: "campaign_6",
    },
    {
        id: "7",
        lifetime_imps: 1200000,
        name: "Ad Set 7",
        targeting: {
            age_max: 25,
            age_min: 18,
            geo_locations: {
                countries: ["US", "MX"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Facebook"],
            facebook_positions: ["Feed", "Story"],
            device_platforms: ["Mobile"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-07-01T00:00:00",
        budget_remaining: "4000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-03-01T12:00:00",
        daily_budget: "100 USD",
        lifetime_budget: "4000 USD",
        promoted_object: {
            page_id: "page_404",
        },
        status: "ACTIVE",
        updated_time: "2024-07-10T10:00:00",
        campaign: {
            id: "campaign_7",
        },
        campaign_id: "campaign_7",
    },
    {
        id: "8",
        lifetime_imps: 1800000,
        name: "Ad Set 8",
        targeting: {
            age_max: 45,
            age_min: 30,
            geo_locations: {
                countries: ["CA", "US"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Instagram"],
            facebook_positions: ["Feed"],
            device_platforms: ["Mobile", "Desktop"],
        },
        effective_status: "PAUSED",
        start_time: "2024-08-01T00:00:00",
        budget_remaining: "6000 USD",
        configured_status: "PAUSED",
        created_time: "2024-04-01T12:00:00",
        daily_budget: "200 USD",
        lifetime_budget: "6000 USD",
        promoted_object: {
            page_id: "page_505",
        },
        status: "PAUSED",
        updated_time: "2024-08-15T10:00:00",
        campaign: {
            id: "campaign_8",
        },
        campaign_id: "campaign_8",
    },
    {
        id: "9",
        lifetime_imps: 2200000,
        name: "Ad Set 9",
        targeting: {
            age_max: 50,
            age_min: 35,
            geo_locations: {
                countries: ["DE", "FR"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Facebook", "Instagram"],
            facebook_positions: ["Feed"],
            device_platforms: ["Desktop"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-09-01T00:00:00",
        budget_remaining: "8000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-05-01T12:00:00",
        daily_budget: "400 USD",
        lifetime_budget: "8000 USD",
        promoted_object: {
            page_id: "page_606",
        },
        status: "ACTIVE",
        updated_time: "2024-09-10T10:00:00",
        campaign: {
            id: "campaign_9",
        },
        campaign_id: "campaign_9",
    },
    {
        id: "10",
        lifetime_imps: 1000000,
        name: "Ad Set 10",
        targeting: {
            age_max: 40,
            age_min: 25,
            geo_locations: {
                countries: ["AU", "NZ"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Facebook"],
            facebook_positions: ["Story"],
            device_platforms: ["Mobile"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-10-01T00:00:00",
        budget_remaining: "7000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-06-01T12:00:00",
        daily_budget: "200 USD",
        lifetime_budget: "7000 USD",
        promoted_object: {
            page_id: "page_707",
        },
        status: "ACTIVE",
        updated_time: "2024-10-05T10:00:00",
        campaign: {
            id: "campaign_10",
        },
        campaign_id: "campaign_10",
    },
];

export const fakeAdsData: TAdsTable[] = [];
