import {
    TAdSetsTable,
    TAdsTable,
    TAdvertisementTable,
    TCampaignTable,
} from "../models/advertisement/advertisement";
import { SelectType } from "../models/common";
import { TSystemTable } from "../models/system/system";

export const fakeSystemTableData: TSystemTable[] = [
    {
        id: "1",
        name: "Công ty cổ phần ABC",
        description: "Công ty chuyên về sản xuất và kinh doanh ABC",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "2",
        name: "Công ty cổ phần BCD",
        description:
            "Công ty chuyên cung cấp dịch vụ BCD trong ngành công nghiệp",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "3",
        name: "Công ty cổ phần EFG",
        description: "Công ty nổi tiếng với sản phẩm công nghệ EFG",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "4",
        name: "Công ty cổ phần XYZ",
        description: "Công ty dẫn đầu trong lĩnh vực phát triển phần mềm XYZ",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "5",
        name: "Công ty cổ phần UVW",
        description: "Công ty chuyên về giải pháp UVW cho doanh nghiệp",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "6",
        name: "Công ty cổ phần RST",
        description: "Công ty hoạt động trong lĩnh vực tài chính RST",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "7",
        name: "Công ty cổ phần LMN",
        description: "Công ty cung cấp dịch vụ viễn thông LMN",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "8",
        name: "Công ty cổ phần OPQ",
        description: "Công ty phát triển công nghệ tiên tiến OPQ",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "9",
        name: "Công ty cổ phần HJK",
        description:
            "Công ty hoạt động trong lĩnh vực sản xuất hàng tiêu dùng HJK",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "10",
        name: "Công ty cổ phần VWX",
        description: "Công ty nổi tiếng với sản phẩm công nghệ VWX",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "11",
        name: "Công ty cổ phần YZA",
        description: "Công ty cung cấp giải pháp môi trường YZA",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
    {
        id: "12",
        name: "Công ty cổ phần BNM",
        description:
            "Công ty dẫn đầu trong lĩnh vực sản xuất và kinh doanh BNM",
        updateDate: "2023-08-29",
        deleteDate: null,
    },
];

export const fakeSelectSystemData: SelectType[] = [
    {
        value: "1",
        label: "Công ty cổ phần VWX",
    },
    {
        value: "2",
        label: "Công ty cổ phần BNM",
    },
    {
        value: "3",
        label: "Công ty cổ phần OPQ",
    },
];

export const fakeSelectAgencyData: SelectType[] = [
    {
        value: "1",
        label: "Chi nhánh cổ phần ABC",
    },
    {
        value: "2",
        label: "Chi nhánh cổ phần DEF",
    },
    {
        value: "3",
        label: "Chi nhánh cổ phần GHI",
    },
];

export const fakeSelectTeamData: SelectType[] = [
    {
        value: "1",
        label: "Đội 1",
    },
    {
        value: "2",
        label: "Đội 2",
    },
    {
        value: "3",
        label: "Đội 3",
    },
];

export const fakeSelectMemberData: SelectType[] = [
    {
        value: "1",
        label: "Member 1",
    },
    {
        value: "2",
        label: "Member 2",
    },
    {
        value: "3",
        label: "Member 3",
    },
];

export const fakeAdvertisementTableData: TAdvertisementTable[] = [
    {
        account_id: "acc_001",
        name: "Account A",
        account_status: 1,
        currency: "USD",
        spend_cap: "10000",
        amount_spent: "5000",
        balance: "2000",
        created_time: "2023-01-10T12:00:00Z",
        owner: "owner_001",
        timezone_name: "America/New_York",
        disable_reason: 0,
        funding_source_details: {
            id: "fund_001",
            display_string: "**** **** **** 1234",
            type: 1,
        },
        min_campaign_group_spend_cap: "100",
        min_daily_budget: 50,
    },
    {
        account_id: "acc_002",
        name: "Account B",
        account_status: 2,
        currency: "EUR",
        spend_cap: "8000",
        amount_spent: "4000",
        balance: "1500",
        created_time: "2022-11-15T08:30:00Z",
        owner: "owner_002",
        timezone_name: "Europe/Berlin",
        disable_reason: 1,
        funding_source_details: {
            id: "fund_002",
            display_string: "**** **** **** 5678",
            type: 2,
        },
        min_campaign_group_spend_cap: "200",
        min_daily_budget: 60,
    },
    {
        account_id: "acc_003",
        name: "Account C",
        account_status: 1,
        currency: "VND",
        spend_cap: "200000000",
        amount_spent: "100000000",
        balance: "50000000",
        created_time: "2023-03-01T10:00:00Z",
        owner: "owner_003",
        timezone_name: "Asia/Ho_Chi_Minh",
        disable_reason: 0,
        funding_source_details: {
            id: "fund_003",
            display_string: "**** **** **** 4321",
            type: 1,
        },
        min_campaign_group_spend_cap: "500000",
        min_daily_budget: 100000,
    },
    {
        account_id: "acc_004",
        name: "Account D",
        account_status: 3,
        currency: "JPY",
        spend_cap: "1200000",
        amount_spent: "600000",
        balance: "300000",
        created_time: "2021-05-20T09:15:00Z",
        owner: "owner_004",
        timezone_name: "Asia/Tokyo",
        disable_reason: 2,
        funding_source_details: {
            id: "fund_004",
            display_string: "**** **** **** 8765",
            type: 3,
        },
        min_campaign_group_spend_cap: "30000",
        min_daily_budget: 5000,
    },
    {
        account_id: "acc_005",
        name: "Account E",
        account_status: 1,
        currency: "GBP",
        spend_cap: "7000",
        amount_spent: "3500",
        balance: "1000",
        created_time: "2020-07-12T07:45:00Z",
        owner: "owner_005",
        timezone_name: "Europe/London",
        disable_reason: 0,
        funding_source_details: {
            id: "fund_005",
            display_string: "**** **** **** 1122",
            type: 2,
        },
        min_campaign_group_spend_cap: "150",
        min_daily_budget: 70,
    },
    {
        account_id: "acc_006",
        name: "Account F",
        account_status: 0,
        currency: "AUD",
        spend_cap: "5000",
        amount_spent: "2500",
        balance: "800",
        created_time: "2019-12-01T14:00:00Z",
        owner: "owner_006",
        timezone_name: "Australia/Sydney",
        disable_reason: 3,
        funding_source_details: {
            id: "fund_006",
            display_string: "**** **** **** 3344",
            type: 1,
        },
        min_campaign_group_spend_cap: "80",
        min_daily_budget: 40,
    },
    {
        account_id: "acc_007",
        name: "Account G",
        account_status: 2,
        currency: "CAD",
        spend_cap: "15000",
        amount_spent: "7500",
        balance: "2500",
        created_time: "2021-02-22T11:00:00Z",
        owner: "owner_007",
        timezone_name: "America/Toronto",
        disable_reason: 1,
        funding_source_details: {
            id: "fund_007",
            display_string: "**** **** **** 5566",
            type: 2,
        },
        min_campaign_group_spend_cap: "300",
        min_daily_budget: 100,
    },
    {
        account_id: "acc_008",
        name: "Account H",
        account_status: 1,
        currency: "CNY",
        spend_cap: "50000",
        amount_spent: "30000",
        balance: "10000",
        created_time: "2022-06-18T06:30:00Z",
        owner: "owner_008",
        timezone_name: "Asia/Shanghai",
        disable_reason: 0,
        funding_source_details: {
            id: "fund_008",
            display_string: "**** **** **** 7788",
            type: 3,
        },
        min_campaign_group_spend_cap: "5000",
        min_daily_budget: 1000,
    },
    {
        account_id: "acc_009",
        name: "Account I",
        account_status: 0,
        currency: "INR",
        spend_cap: "300000",
        amount_spent: "150000",
        balance: "40000",
        created_time: "2023-04-12T13:00:00Z",
        owner: "owner_009",
        timezone_name: "Asia/Kolkata",
        disable_reason: 3,
        funding_source_details: {
            id: "fund_009",
            display_string: "**** **** **** 9911",
            type: 1,
        },
        min_campaign_group_spend_cap: "10000",
        min_daily_budget: 5000,
    },
    {
        account_id: "acc_010",
        name: "Account J",
        account_status: 2,
        currency: "SGD",
        spend_cap: "20000",
        amount_spent: "10000",
        balance: "2500",
        created_time: "2021-10-30T10:15:00Z",
        owner: "owner_010",
        timezone_name: "Asia/Singapore",
        disable_reason: 1,
        funding_source_details: {
            id: "fund_010",
            display_string: "**** **** **** 6677",
            type: 2,
        },
        min_campaign_group_spend_cap: "600",
        min_daily_budget: 150,
    },
];

export const fakeCampaignTableData: TCampaignTable[] = [
    {
        id: "C001",
        name: "Campaign 1",
        budget_rebalance_flag: true,
        buying_type: "AUCTION",
        created_time: "2023-01-10T08:30:00Z",
        start_time: "2023-02-01T09:00:00Z",
        effective_status: "ACTIVE",
        configured_status: "PAUSED",
        status: "ACTIVE",
        account_id: "A001",
        budget_remaining: "5000",
        special_ad_category_country: ["US", "CA"],
        updated_time: "2023-09-01T10:00:00Z",
    },
    {
        id: "C002",
        name: "Campaign 2",
        budget_rebalance_flag: false,
        buying_type: "FIXED_CPM",
        created_time: "2023-03-12T11:15:00Z",
        start_time: "2023-03-15T12:00:00Z",
        effective_status: "PAUSED",
        configured_status: "ACTIVE",
        status: "PAUSED",
        account_id: "A002",
        budget_remaining: "2000",
        special_ad_category_country: ["GB", "FR"],
        updated_time: "2023-08-20T14:30:00Z",
    },
    {
        id: "C003",
        name: "Campaign 3",
        budget_rebalance_flag: true,
        buying_type: "AUCTION",
        created_time: "2023-05-08T07:45:00Z",
        start_time: "2023-05-12T08:00:00Z",
        effective_status: "ACTIVE",
        configured_status: "ACTIVE",
        status: "ACTIVE",
        account_id: "A003",
        budget_remaining: "10000",
        special_ad_category_country: ["DE"],
        updated_time: "2023-08-10T09:30:00Z",
    },
    {
        id: "C004",
        name: "Campaign 4",
        budget_rebalance_flag: false,
        buying_type: "RESERVE",
        created_time: "2023-06-05T10:00:00Z",
        start_time: "2023-06-10T11:00:00Z",
        effective_status: "DISABLED",
        configured_status: "DISABLED",
        status: "DISABLED",
        account_id: "A004",
        budget_remaining: "0",
        special_ad_category_country: ["JP"],
        updated_time: "2023-09-05T13:45:00Z",
    },
    {
        id: "C005",
        name: "Campaign 5",
        budget_rebalance_flag: true,
        buying_type: "AUCTION",
        created_time: "2023-04-25T09:30:00Z",
        start_time: "2023-05-01T10:00:00Z",
        effective_status: "ACTIVE",
        configured_status: "ACTIVE",
        status: "ACTIVE",
        account_id: "A005",
        budget_remaining: "7500",
        special_ad_category_country: ["AU", "NZ"],
        updated_time: "2023-09-07T11:20:00Z",
    },
    {
        id: "C006",
        name: "Campaign 6",
        budget_rebalance_flag: false,
        buying_type: "FIXED_CPM",
        created_time: "2023-02-17T12:00:00Z",
        start_time: "2023-02-20T13:00:00Z",
        effective_status: "PAUSED",
        configured_status: "ACTIVE",
        status: "PAUSED",
        account_id: "A006",
        budget_remaining: "1200",
        special_ad_category_country: ["IN"],
        updated_time: "2023-08-28T14:30:00Z",
    },
    {
        id: "C007",
        name: "Campaign 7",
        budget_rebalance_flag: true,
        buying_type: "AUCTION",
        created_time: "2023-07-15T06:45:00Z",
        start_time: "2023-07-20T07:00:00Z",
        effective_status: "ACTIVE",
        configured_status: "ACTIVE",
        status: "ACTIVE",
        account_id: "A007",
        budget_remaining: "6500",
        special_ad_category_country: ["US"],
        updated_time: "2023-09-04T12:00:00Z",
    },
    {
        id: "C008",
        name: "Campaign 8",
        budget_rebalance_flag: false,
        buying_type: "RESERVE",
        created_time: "2023-01-25T14:30:00Z",
        start_time: "2023-02-01T15:00:00Z",
        effective_status: "DISABLED",
        configured_status: "DISABLED",
        status: "DISABLED",
        account_id: "A008",
        budget_remaining: "0",
        special_ad_category_country: ["BR"],
        updated_time: "2023-08-15T16:45:00Z",
    },
    {
        id: "C009",
        name: "Campaign 9",
        budget_rebalance_flag: true,
        buying_type: "AUCTION",
        created_time: "2023-06-30T10:15:00Z",
        start_time: "2023-07-05T11:00:00Z",
        effective_status: "ACTIVE",
        configured_status: "ACTIVE",
        status: "ACTIVE",
        account_id: "A009",
        budget_remaining: "8500",
        special_ad_category_country: ["IT", "ES"],
        updated_time: "2023-09-06T17:30:00Z",
    },
    {
        id: "C010",
        name: "Campaign 10",
        budget_rebalance_flag: false,
        buying_type: "FIXED_CPM",
        created_time: "2023-03-21T11:45:00Z",
        start_time: "2023-03-25T12:00:00Z",
        effective_status: "PAUSED",
        configured_status: "ACTIVE",
        status: "PAUSED",
        account_id: "A010",
        budget_remaining: "3000",
        special_ad_category_country: ["KR"],
        updated_time: "2023-08-19T13:00:00Z",
    },
];

export const fakeAdSetsTableData: TAdSetsTable[] = [
    {
        id: "1",
        lifetime_imps: 1000000,
        name: "Ad Set 1",
        targeting: {
            age_max: 35,
            age_min: 18,
            geo_locations: {
                countries: ["US", "CA"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Facebook", "Instagram"],
            facebook_positions: ["Feed", "Story"],
            device_platforms: ["Mobile", "Desktop"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-01-01T00:00:00",
        budget_remaining: "5000 USD",
        configured_status: "ACTIVE",
        created_time: "2023-12-01T12:00:00",
        daily_budget: "100 USD",
        lifetime_budget: "5000 USD",
        promoted_object: {
            page_id: "page_123",
        },
        status: "ACTIVE",
        updated_time: "2024-01-10T10:00:00",
        campaign: {
            id: "campaign_1",
        },
        campaign_id: "campaign_1",
    },
    {
        id: "2",
        lifetime_imps: 1500000,
        name: "Ad Set 2",
        targeting: {
            age_max: 45,
            age_min: 25,
            geo_locations: {
                countries: ["GB", "AU"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Facebook"],
            facebook_positions: ["Feed"],
            device_platforms: ["Desktop"],
        },
        effective_status: "PAUSED",
        start_time: "2024-02-01T00:00:00",
        budget_remaining: "3000 USD",
        configured_status: "PAUSED",
        created_time: "2023-11-01T12:00:00",
        daily_budget: "50 USD",
        lifetime_budget: "3000 USD",
        promoted_object: {
            page_id: "page_456",
        },
        status: "PAUSED",
        updated_time: "2024-02-15T10:00:00",
        campaign: {
            id: "campaign_2",
        },
        campaign_id: "campaign_2",
    },
    {
        id: "3",
        lifetime_imps: 2000000,
        name: "Ad Set 3",
        targeting: {
            age_max: 30,
            age_min: 20,
            geo_locations: {
                countries: ["FR", "DE"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Instagram"],
            facebook_positions: ["Story"],
            device_platforms: ["Mobile"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-03-01T00:00:00",
        budget_remaining: "8000 USD",
        configured_status: "ACTIVE",
        created_time: "2023-10-01T12:00:00",
        daily_budget: "200 USD",
        lifetime_budget: "8000 USD",
        promoted_object: {
            page_id: "page_789",
        },
        status: "ACTIVE",
        updated_time: "2024-03-05T10:00:00",
        campaign: {
            id: "campaign_3",
        },
        campaign_id: "campaign_3",
    },
    {
        id: "4",
        lifetime_imps: 500000,
        name: "Ad Set 4",
        targeting: {
            age_max: 40,
            age_min: 30,
            geo_locations: {
                countries: ["IT", "ES"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Facebook", "Instagram"],
            facebook_positions: ["Feed"],
            device_platforms: ["Mobile", "Desktop"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-04-01T00:00:00",
        budget_remaining: "2000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-01-01T12:00:00",
        daily_budget: "50 USD",
        lifetime_budget: "2000 USD",
        promoted_object: {
            page_id: "page_101",
        },
        status: "ACTIVE",
        updated_time: "2024-04-10T10:00:00",
        campaign: {
            id: "campaign_4",
        },
        campaign_id: "campaign_4",
    },
    {
        id: "5",
        lifetime_imps: 750000,
        name: "Ad Set 5",
        targeting: {
            age_max: 50,
            age_min: 40,
            geo_locations: {
                countries: ["JP", "KR"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Facebook"],
            facebook_positions: ["Feed"],
            device_platforms: ["Desktop"],
        },
        effective_status: "PAUSED",
        start_time: "2024-05-01T00:00:00",
        budget_remaining: "1500 USD",
        configured_status: "PAUSED",
        created_time: "2023-12-01T12:00:00",
        daily_budget: "30 USD",
        lifetime_budget: "1500 USD",
        promoted_object: {
            page_id: "page_202",
        },
        status: "PAUSED",
        updated_time: "2024-05-15T10:00:00",
        campaign: {
            id: "campaign_5",
        },
        campaign_id: "campaign_5",
    },
    {
        id: "6",
        lifetime_imps: 3000000,
        name: "Ad Set 6",
        targeting: {
            age_max: 60,
            age_min: 30,
            geo_locations: {
                countries: ["BR", "AR"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Instagram"],
            facebook_positions: ["Story"],
            device_platforms: ["Mobile"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-06-01T00:00:00",
        budget_remaining: "10000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-02-01T12:00:00",
        daily_budget: "500 USD",
        lifetime_budget: "10000 USD",
        promoted_object: {
            page_id: "page_303",
        },
        status: "ACTIVE",
        updated_time: "2024-06-05T10:00:00",
        campaign: {
            id: "campaign_6",
        },
        campaign_id: "campaign_6",
    },
    {
        id: "7",
        lifetime_imps: 1200000,
        name: "Ad Set 7",
        targeting: {
            age_max: 25,
            age_min: 18,
            geo_locations: {
                countries: ["US", "MX"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Facebook"],
            facebook_positions: ["Feed", "Story"],
            device_platforms: ["Mobile"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-07-01T00:00:00",
        budget_remaining: "4000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-03-01T12:00:00",
        daily_budget: "100 USD",
        lifetime_budget: "4000 USD",
        promoted_object: {
            page_id: "page_404",
        },
        status: "ACTIVE",
        updated_time: "2024-07-10T10:00:00",
        campaign: {
            id: "campaign_7",
        },
        campaign_id: "campaign_7",
    },
    {
        id: "8",
        lifetime_imps: 1800000,
        name: "Ad Set 8",
        targeting: {
            age_max: 45,
            age_min: 30,
            geo_locations: {
                countries: ["CA", "US"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Instagram"],
            facebook_positions: ["Feed"],
            device_platforms: ["Mobile", "Desktop"],
        },
        effective_status: "PAUSED",
        start_time: "2024-08-01T00:00:00",
        budget_remaining: "6000 USD",
        configured_status: "PAUSED",
        created_time: "2024-04-01T12:00:00",
        daily_budget: "200 USD",
        lifetime_budget: "6000 USD",
        promoted_object: {
            page_id: "page_505",
        },
        status: "PAUSED",
        updated_time: "2024-08-15T10:00:00",
        campaign: {
            id: "campaign_8",
        },
        campaign_id: "campaign_8",
    },
    {
        id: "9",
        lifetime_imps: 2200000,
        name: "Ad Set 9",
        targeting: {
            age_max: 50,
            age_min: 35,
            geo_locations: {
                countries: ["DE", "FR"],
            },
            targeting_automation: {
                advantage_audience: 1,
            },
            publisher_platforms: ["Facebook", "Instagram"],
            facebook_positions: ["Feed"],
            device_platforms: ["Desktop"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-09-01T00:00:00",
        budget_remaining: "8000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-05-01T12:00:00",
        daily_budget: "400 USD",
        lifetime_budget: "8000 USD",
        promoted_object: {
            page_id: "page_606",
        },
        status: "ACTIVE",
        updated_time: "2024-09-10T10:00:00",
        campaign: {
            id: "campaign_9",
        },
        campaign_id: "campaign_9",
    },
    {
        id: "10",
        lifetime_imps: 1000000,
        name: "Ad Set 10",
        targeting: {
            age_max: 40,
            age_min: 25,
            geo_locations: {
                countries: ["AU", "NZ"],
            },
            targeting_automation: {
                advantage_audience: 0,
            },
            publisher_platforms: ["Facebook"],
            facebook_positions: ["Story"],
            device_platforms: ["Mobile"],
        },
        effective_status: "ACTIVE",
        start_time: "2024-10-01T00:00:00",
        budget_remaining: "7000 USD",
        configured_status: "ACTIVE",
        created_time: "2024-06-01T12:00:00",
        daily_budget: "200 USD",
        lifetime_budget: "7000 USD",
        promoted_object: {
            page_id: "page_707",
        },
        status: "ACTIVE",
        updated_time: "2024-10-05T10:00:00",
        campaign: {
            id: "campaign_10",
        },
        campaign_id: "campaign_10",
    },
];

export const fakeAdsData: TAdsTable[] = [
    {
        id: "1",
        adset_id: "201",
        name: "Ad A",
        status: "Active",
        effective_status: "Serving",
        adcreatives: "Creative A",
        created_time: "2024-05-01",
        updated_time: "2024-09-01 10:00:00",
        start_time: "2024-05-05",
    },
    {
        id: "2",
        adset_id: "202",
        name: "Ad B",
        status: "Inactive",
        effective_status: "Paused",
        adcreatives: "Creative B",
        created_time: "2024-06-01",
        updated_time: "2024-09-02 11:30:00",
        start_time: "2024-06-10",
    },
    {
        id: "3",
        adset_id: "203",
        name: "Ad C",
        status: "Active",
        effective_status: "Serving",
        adcreatives: "Creative C",
        created_time: "2024-07-01",
        updated_time: "2024-09-03 09:45:00",
        start_time: "2024-07-05",
    },
    {
        id: "4",
        adset_id: "204",
        name: "Ad D",
        status: "Active",
        effective_status: "Serving",
        adcreatives: "Creative D",
        created_time: "2024-08-01",
        updated_time: "2024-09-04 08:20:00",
        start_time: "2024-08-10",
    },
    {
        id: "5",
        adset_id: "205",
        name: "Ad E",
        status: "Inactive",
        effective_status: "Paused",
        adcreatives: "Creative E",
        created_time: "2024-09-01",
        updated_time: "2024-09-05 12:00:00",
        start_time: "2024-09-10",
    },
    {
        id: "6",
        adset_id: "206",
        name: "Ad F",
        status: "Active",
        effective_status: "Serving",
        adcreatives: "Creative F",
        created_time: "2024-09-05",
        updated_time: "2024-09-06 14:15:00",
        start_time: "2024-09-15",
    },
    {
        id: "7",
        adset_id: "207",
        name: "Ad G",
        status: "Inactive",
        effective_status: "Paused",
        adcreatives: "Creative G",
        created_time: "2024-09-10",
        updated_time: "2024-09-07 16:40:00",
        start_time: "2024-09-20",
    },
    {
        id: "8",
        adset_id: "208",
        name: "Ad H",
        status: "Active",
        effective_status: "Serving",
        adcreatives: "Creative H",
        created_time: "2024-09-15",
        updated_time: "2024-09-08 10:50:00",
        start_time: "2024-09-25",
    },
    {
        id: "9",
        adset_id: "209",
        name: "Ad I",
        status: "Active",
        effective_status: "Serving",
        adcreatives: "Creative I",
        created_time: "2024-09-20",
        updated_time: "2024-09-09 11:10:00",
        start_time: "2024-09-30",
    },
    {
        id: "10",
        adset_id: "210",
        name: "Ad J",
        status: "Inactive",
        effective_status: "Paused",
        adcreatives: "Creative J",
        created_time: "2024-09-25",
        updated_time: "2024-09-10 13:05:00",
        start_time: "2024-10-05",
    },
];
